### ISSUE TITLE
Street scale issue

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#1001]
## Context

<img width="1672" alt="screen shot 2017-09-27 at 14 57 04" src="https://user-images.githubusercontent.com/20966824/30918535-7ec419ec-a3a7-11e7-890a-c7ffac3a2ffd.png">

## Steps to reproduce

1) open dollar street home page
2) decrease the zoom so you fit 9 houses in a row
3) observe black houses on the street that are placed roughly at equal distances on screen. They have incomes: 27, 68, 201, 578, 2001
4) divide 68/27 so you get a sense of scale, you get 2.5
5) this means there must be 2.5x ratio between the black houses
6) it’s not so!

## Possible Fix

var incomes = [1, 2, 20, 200, 2000] //dollars
var width = 1024; //px

var positionsOnTheStreet = incomes.map((i) => Math.log10(i) * width/Math.log10(Math.max(...incomes))) ;

console.log(positionsOnTheStreet)

## Platform
Any

## Browsers
Any

**Comment by jheeffer** [comment]
Ask @angieskazka or me on slack if problem is not clear

**Comment by dmitryuck** [comment]
thanks, today going to investigate this, if any issues appear I'll ask

2017-09-27 22:02 GMT+03:00 Jasper Heeffer <notifications@github.com>:
