### ISSUE TITLE
Embed feature: impossible to select images from the first row

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/dollar-street-pages#1043]
## Context

When no images selected - the only tiny piece of the heart icon is visible. When 2 or more images selected - header simply overlaps the icons so user can't select any.
Maybe add some kind of autoscroll if header overlaps the first row?

## Steps to reproduce

1. Scroll down page a bit (to reveal floating header with the heart icon)
2. Select two images
3. Select image from the first row

## Expected result

Should be possible

## Current result

Header overlaps the heart icon

## Platform
Desktop
## Browsers
any
## screenshot

![selection_143](https://user-images.githubusercontent.com/18219232/31432057-392e8138-ae7e-11e7-98f3-dccd98138c88.png)

**Comment by sergeyKhristenko** [comment]
For now, If Welcome wizard is ON, there will be a gap

![selection_251](https://user-images.githubusercontent.com/18219232/32110452-3d58c4e8-bb40-11e7-8da8-e43309456bcd.png)

Steps:
1. Activate Welcome wizard
2. Click on Heart icon in the floating footer

**Comment by dmitryuck** [comment]
this is an issue in combination with quick guide
