### ISSUE TITLE
House stays active on street even it's outside new filter settings

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/dollar-street-pages#1107]
## Context

"Active" house stays active when street filter set to range which doesn't include active house.

![image](https://user-images.githubusercontent.com/1596071/32454256-fb2ec50e-c31e-11e7-9d2f-938ab240766f.png)

(in rest of page, no photo is expanded/folded out).

## Steps to reproduce

1. Go to http://www.gapminder.org/dollar-street/

2. Click on a photo so that the bigger version becomes visible. This house is now active on the street (bigger & coloured).
3. Drag one side of the street so the filter doesn't include the active house anymore.

OR 

1. Go to http://www.gapminder.org/dollar-street/
2. Drag one side or both sides of the street so only a small part is selected
3. Click on a photo so that the bigger version becomes visible. This house is now active on the street (bigger & coloured).
4. Drag the filter over the street (by clicking in the middle of it and dragging) so the filter doesn't include the active house anymore.

## Expected result

An active house on the street should become inactive if it's not included in new filter settings

## Current result

The house stays active after new filter settings

## Platform

Windows

## Browsers

Chrome

**Comment by sergeyKhristenko** [comment]
Related to https://github.com/Gapminder/dollar-street-pages/issues/1033
