### ISSUE TITLE
Embed: Change design of page when user comes to Dollar Street through a social media embed link (see below).

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#1138]
![pasted image 0](https://user-images.githubusercontent.com/20966824/33164811-21275eda-d03d-11e7-94e2-fbe874835f47.png)

**Comment by sergeyKhristenko** [comment]
IE 11
![selection_053](https://user-images.githubusercontent.com/18219232/33612701-1a54d306-d9db-11e7-820a-b8846dfc8d8a.png)

**Comment by sergeyKhristenko** [comment]
IE 11
![selection_100](https://user-images.githubusercontent.com/18219232/34732280-7d3d9de2-f56d-11e7-8e75-daacedfa81a6.png)
