### ISSUE TITLE
Embed: Add Quick guide to Dollar Street in the upper right corner under the x

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#1139]
Add Quick guide to Dollar Street in the upper right corner under the x. Exactly how that opens I will can not foresee at this point.

![pasted image 0](https://user-images.githubusercontent.com/20966824/33164873-5ac2de12-d03d-11e7-9350-a6455f31885b.png)

**Comment by sergeyKhristenko** [comment]
![selection_004](https://user-images.githubusercontent.com/18219232/33551064-d165dcb8-d8f8-11e7-9f73-90479cca2591.png)

Steps:
1. Follow shared link (use this: http://ds-dev.dollarstreet.org/dollar-street/matrix?thing=Families&countries=World&regions=World&zoom=4&row=1&lowIncome=26&highIncome=15000&lang=en&embed=5a2530019150fc4e1ee43ba2)
2. Click on 'quick guide'
3. Press Back in browser
What page should see user now? The same as was opened after step 1?

-------------------
add step to history browser when we open quick guide

**Comment by Miffael** [comment]
share window is modal, and you don't change page when close it. different between close button and 'quick guide' - show or not quick guide when modal is closed
