### ISSUE TITLE
Family page. Click on any image

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#1166]
## Context

![selection_027](https://user-images.githubusercontent.com/20966824/33600976-8cf3806a-d9b3-11e7-9736-db4b905a6a80.png)

## Steps to reproduce

1. Open matrix
2. Visit any home
3. Click on any image

## Current result

Click action produces an error in console

## Browsers

Any

**Comment by sergeyKhristenko** [comment]
Not only on image but anywhere on the page
