### ISSUE TITLE
Mobile: Street widget should have smaller icons and be less hight

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/dollar-street-pages#119]
According to https://projects.invisionapp.com/share/WN6FQDL2X#/screens/142251790 design Street widget should have smaller icons and be less hight.

**Comment by ghost** [comment]
![snap93](https://cloud.githubusercontent.com/assets/16382915/14047636/b327cfec-f2b1-11e5-9d9c-0d7d2fcf8085.png)
