### ISSUE TITLE
Italian Translations

### ISSUE THREAD

**Issue by michaelasumcinei** [Gapminder/dollar-street-pages#1222]
Hello

I would like to contribute with Italian translations.

I can do that only using Github as I am an adopter of Utopian.io project to reward open source software.

Just let me know if you are interested and I will be there for it

Best Regards
Michael Asumcinei
steemit.com/@digitalplayer

**Comment by Miffael** [comment]
We don't have translations in this project, please create request in our Crowdin project https://crowdin.com/project/dollar-street , you can contact our manager there https://crowdin.com/profile/hishamnajam
