### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by navxx** [Gapminder/dollar-street-pages#1229]
Hello!

I've been following your project and it is a great one!

I want to be part of it. My contribution could be the spanish translation. The thing is, I need to know what documents need to be translated, I saw that there is a License in English, I can start with that if you want, or I can translate those files you have in crowdin, you are the boss.

Best regards!

**Comment by Miffael** [comment]
We don't have translations in this project, please create request in our Crowdin project https://crowdin.com/project/dollar-street , you can contact our manager there https://crowdin.com/profile/hishamnajam
