### ISSUE TITLE
Info page: consumer

### ISSUE THREAD

**Issue by Betrozov** [Gapminder/dollar-street-pages#304]
## Context

[provide more detailed introduction to the issue itself and why it is relevant]
## Steps to reproduce

[ordered list the process to finding and recreating the issue, example below]
1. User goes to delete a dataset (to save space or whatever)
2. User gets popup modal warning
3. User deletes and it's lost forever
## Expected result

[describe what you would expect to have resulted from this process]
## Current result

[describe what you you currently experience from this process, and thereby explain the bug]
## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]
## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by ludmilanesvitiy** [comment]
![screenshot from 2016-05-18 14 52 51](https://cloud.githubusercontent.com/assets/18209841/15357564/47b2b390-1d08-11e6-812b-74645d29e1be.png)
Have some problems with Mobile and Tablet version on this page.
