### ISSUE TITLE
Consumer: close menu

### ISSUE THREAD

**Issue by Ugmaxie** [Gapminder/dollar-street-pages#377]
## Context

Make menu disappear when `home` is `infocus`.
## Steps to reproduce
1. User goes to `Homes` by nav button in header.
2. Click on `Menu` icon button in the top right coner.
3. Move mouse to a row of homes.
4. When any home is in focus, menu has to disappear.
## Expected result

When any home is in focus, menu has to disappear.
## Current result

 When any home is in focus, menu doesn't disappear.
## Possible Fix

Check if menu is **opened** while moving mouse by row of homes.
If **menu** is opened and any **home** is in focus - close menu.
## Platform

Linux Mint 64@latest
## Browsers

Chrome@latest

**Comment by ludmilanesvitiy** [comment]
Need to fix it on Mobile, Tablet
