### ISSUE TITLE
Matrix Page: after opening big section, screen doesn't scroll down, when quantity of families less than 5.

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#564]
## Context

Matrix Page: after opening big section, screen doesn't scroll down, when quantity of families less than 5.
## Steps to reproduce
1. Open Matrix.
2. Choose the thing Agriculture land.
3. Choose the region Europe.
4. Click on some photo.
## Expected result

Big section should be always visible, page should scrolling to top.
## Platform

Linux Mint
## Browsers

Chrome, Mozilla FF
## `name of issue` screenshot

![screenshot from 2016-08-16 12 41 31](https://cloud.githubusercontent.com/assets/18209841/17694934/e7f75148-63ae-11e6-9192-af4c4f88b3e8.png)

**Comment by ludmilanesvitiy** [comment]
Still reproducible.

**Comment by dmitryuck** [comment]
resolved
