### ISSUE TITLE
Matrix Page: after some actions, incomes stay NaN

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#570]
## Context

Matrix Page: after some actions, incomes stay NaN
## Steps to reproduce

User can get this page:
http://consumer.dollarstreet.org/matrix?thing=Toys&countries=Afghanistan,Pakistan&regions=World&zoom=4&row=1&lowIncome=NaN&highIncome=NaN
1. Open Matrix.
2. Choose thing "Toys"
3. Move left toddler to the right (for example to 1000)
4. In Country filter select Asia region and after deselect all active countries (selected will be only Afganistan and Pakistan). Apply filter and you get the link with NaN incomes.
## Platform

Linux Mint
## Browsers

Chrome, Mozilla

**Comment by ludmilanesvitiy** [comment]
For now, we couldn't have NaN, but we will get the street with active dark-grey houses.
![screenshot from 2016-10-11 15 35 46](https://cloud.githubusercontent.com/assets/18209841/19270431/b4394da2-8fc8-11e6-9d82-1cf4b53ea377.png)

**Comment by Legionivo** [comment]
Unable to reproduce
