### ISSUE TITLE
Quick guide on Nexus 7: Poorest and Richest (on 1 step).  

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#607]
## Context

Quick guide on Nexus 7: Poorest and Richest (on 1 step).
First bubble placing on the Poorest an Richest  
## Steps to reproduce
1. Quick guide: Open 1st step. Look at the bubble and Poorest, Richest 
## Platform

Chrome emulator, Nexus 7 only
## Browsers

Chrome
## `name of issue` screenshot

![screen shot 2016-09-01 at 2 51 05 pm](https://cloud.githubusercontent.com/assets/18209841/18166431/d57dd904-7053-11e6-8fbe-a876ac976338.png)

**Comment by Legionivo** [comment]
Unable to reproduce
