### ISSUE TITLE
Matrix Page scroll: Microsoft Edge

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#665]
## Context

Scroll on Matrix Page works bad on Microsoft Edge (at scrolling, page always jumps to top)
## Steps to reproduce
1. Open Matrix
2. Try to scrolling
## Platform

Windows 10, VMware
## Browsers

IEdge 38.143

**Comment by Legionivo** [comment]
Fixed on dev
