### ISSUE TITLE
Matrix Page, Street: after dropping incomes, first toddler isn't visible

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#668]
## Context

Matrix Page, Street: after dropping incomes, first toddler isn't visible
## Steps to reproduce
1. Open Matrix.
2. Move toddlers to empty interval (without visible homes).
3. Toddlers rebuilds and should stay from the lowest to richest in current selection. But you couldn't see the first toddler.
## Expected result

Toddlers should be always visible.
## Platform

Linux, Desktop
## Browsers

Chrome, Mozilla
## `name of issue` screenshot

![screenshot from 2016-10-17 13 52 22](https://cloud.githubusercontent.com/assets/18209841/19434973/126ee93e-9471-11e6-93a8-c8a1a9608df7.png)

**Comment by ludmilanesvitiy** [comment]
After dropping incomes, we get an errors in console, as on Desktop, as on Mobile:
![screenshot from 2016-10-18 13 46 24](https://cloud.githubusercontent.com/assets/18209841/19474774/c53f5f4e-9539-11e6-96e4-1b34c1225853.png)
![screenshot from 2016-10-18 13 47 41](https://cloud.githubusercontent.com/assets/18209841/19474775/c5425ff0-9539-11e6-88eb-1b613f1be760.png)

For reproducing it, you should Open Matrix, Move left toddler to 1000$ and choose Burkina Faso in country filter.

**Comment by Legionivo** [comment]
@bogdankatrych reproduced

**Comment by Legionivo** [comment]
reproduced

**Comment by Legionivo** [comment]
Verified - fixed
