### ISSUE TITLE
Street Widget, Iphone 6: doesn't rebuilds after changing thing in filter.

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#670]
## Context

Street Widget, Iphone 6: doesn't rebuilds after changing thing in filter.
## Steps to reproduce
1. Open Matrix.
2. Change the poorest income to 1000 $.
3. Open BIS in India and click "All families in India".
4. Change thing in filter. You'll see this:
   ![screenshot from 2016-10-18 10 45 08](https://cloud.githubusercontent.com/assets/18209841/19468682/7198ff8a-9520-11e6-9a4e-cc7e333e612c.png)
## Expected result

After page reload, you'll see:
![screenshot from 2016-10-18 10 49 09](https://cloud.githubusercontent.com/assets/18209841/19468718/9392c9d6-9520-11e6-8414-cf0c3bda966d.png)
## Platform

Linux Chrome emulator Iphone 6
## Browsers

Chrome

**Comment by Legionivo** [comment]
unable to reproduce
