### ISSUE TITLE
Country filter: select button jumping after clicks on it

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#672]
## Context

Country filter: select button jumping after clicks on it
## Steps to reproduce
1. Open Matrix
2. Open Country filter.
3. Click on region (Asia, Africa, etc.) Look what happens with Select Button, when you clicks on it. It should be on the same place.
   It happens on desktop filter and on resized filter.
## Platform

Linux Mint
## Browsers

Chrome
## `name of issue` screenshot

![screenshot from 2016-10-18 13 58 52](https://cloud.githubusercontent.com/assets/18209841/19475350/4be5c23e-953c-11e6-9881-18141f415727.png)
![screenshot from 2016-10-18 13 58 56](https://cloud.githubusercontent.com/assets/18209841/19475349/4be3b58e-953c-11e6-9e75-1a7b2ab395df.png)

**Comment by Legionivo** [comment]
Unable to reproduce
