### ISSUE TITLE
Matrix Page, Street Widget: visible houses are not rebuilds

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#673]
## Context

Matrix Page, Street Widget: visible houses are not rebuilds (when quantity of photos less than on one visible screen)
## Steps to reproduce
1. Open Matrix.
2. Choose Cambodia.
3. Move left toddler to right or vice versa. You'll see  Street Widget with dark grey houses, which aren't visible on Matrix.
## Current result

![screenshot from 2016-10-18 14 09 06](https://cloud.githubusercontent.com/assets/18209841/19476033/bfaee6c0-953f-11e6-93ad-604a1025087e.png)
## Expected result

Works after reloading page
![screenshot from 2016-10-18 14 33 58](https://cloud.githubusercontent.com/assets/18209841/19476066/fa51b4d8-953f-11e6-9557-1f808405a6cf.png)
## Platform

Linux Mint, Desktop
Emulator iPad, Iphone 6, other mobile and Desktop
## Browsers

Chrome

**Comment by Legionivo** [comment]
![07_11_12 25 15_01](https://user-images.githubusercontent.com/12167296/28061655-035b39ee-6634-11e7-8d39-bef6743018ec.png)

**Comment by Legionivo** [comment]
@bogdankatrych reproduced

**Comment by Legionivo** [comment]
Verified - fixed
