### ISSUE TITLE
Matrix Page, Bubbles: when welcome header not fully visible, first step goes to top

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#675]
## Context

Matrix Page, Bubbles: when welcome header not fully visible, first step goes to top
## Steps to reproduce

[ordered list the process to finding and recreating the issue, example below]
1. Open Matrix with welcome header.
2. Scroll down a little
3. Click "Quick tour" and see at the first bubble. You'll see it not full and "Richest" and "Poorest" will not at his places.
## Current result

![screenshot from 2016-10-19 12 13 57](https://cloud.githubusercontent.com/assets/18209841/19512673/ad591f2a-95f5-11e6-975a-750df172a4b0.png)
## Platform

Desktop, Tablet, Mobile
## Browsers

Chrome

**Comment by Legionivo** [comment]
Unable to reproduce
