### ISSUE TITLE
Matrix Page, main photo in BIS: loads correct not always

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#676]
## Context

Matrix Page, main photo in BIS: loads correct not always
## Steps to reproduce
1. Open Matrix.
2. Open some BIS. Only at first you can see the blur-up effect on photo (when at first loads blur photo, and then gets more qualitative image). On another families, when you'll click BIS will shown the previous photo (from last BIS) and then (in a few sec), it'll reloads to current family.
## Current result

When you open BIS at first:
![screenshot from 2016-10-19 12 18 52](https://cloud.githubusercontent.com/assets/18209841/19513097/6bda7ff6-95f7-11e6-9523-94819be86969.png)
When you open BIS next time:
![screenshot from 2016-10-19 12 28 33](https://cloud.githubusercontent.com/assets/18209841/19513168/b131b2a4-95f7-11e6-9d8a-2b95b6a06670.png)
## Platform

All
## Browsers

Chrome

**Comment by Legionivo** [comment]
Fixed
