### ISSUE TITLE
Family Page: BIS doesn't open fully in the visible screen

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#702]
## Context

After some actions on family Page: BIS doesn't open fully in the visible screen
## Steps to reproduce
1. Open some Family Page.
2. Click on the family icon in header.
3. Look at the BIS and click to the little family icon in little header for closing this BIS.
4. After closing BIS, click on some photo on the last visible row in this screen, which visible not fully. And you'll see the BIS, which have opened not at all screen.
## Current result

![screenshot from 2016-10-27 14 40 00](https://cloud.githubusercontent.com/assets/18209841/19766247/79b14042-9c55-11e6-8a91-b68ecb5afa51.png)
## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]
## Platform

Linux Mint
## Browsers

Chrome, Firefox

**Comment by Legionivo** [comment]
already fixed
