### ISSUE TITLE
Matrix Page, URL: after reloading page (F5), row decreases on 1

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#708]
## Context

Matrix Page, URL: after reloading page (F5), row decreases on 1

## Steps to reproduce

1. Open Matrix with opened WElcome header (it's important)
2. Scroll down to some row N
3. Click F5 and look at URL: it'll be (N-1). But should stay at the same row.

## Expected result

Row number stays the same after reloading page

## Platform
Linux Mint
## Browsers
Chrome (only)

**Comment by Legionivo** [comment]
@bogdankatrych reproduced

**Comment by Legionivo** [comment]
Verified - fixed
