### ISSUE TITLE
Matrix Page, hover with description about thing doesn't appear

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#709]
## Context

Matrix Page, hover with description about thing doesn't appear

## Steps to reproduce

1. Open Matrix on small screen (we need to open thing filter with tablet format)
2. Choose some thing with description (for example Books, Beds)
3. Move mouse to button with thing filter and description will not appear (it happens only when we choose thing from filter with tablet format).

## Expected result

Hover with description of thing appears always on Desktop.

## Platform
Linux Mint
## Browsers
Chrome, Mozilla

**Comment by Legionivo** [comment]
Reproduced

**Comment by Legionivo** [comment]
Verified - fixed
