### ISSUE TITLE
Photographer profile: list of visited families shows bad (IPhone 6)

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#710]
## Context

Photographer profile: Jonathan Taylor: list of visited families shows bad

## Steps to reproduce

1. Open profile Jonathan Taylor on iPhone 6: 
http://m.gapminder.org/dollar-street/photographer/56ec0917af72e9437cbccf94
2. Look at the list of families.

## Current result

![screenshot from 2016-11-02 10 23 55](https://cloud.githubusercontent.com/assets/18209841/19921439/97d30cdc-a0e6-11e6-97fc-ed337679ae60.png)

## Platform
Mobile iPhone6
## Browsers
Chrome

**Comment by Legionivo** [comment]
Unable to reproduce
