### ISSUE TITLE
Back button on Mobile, Tablet from matrix to country page

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#721]
## Context

After some actions, back button works only after second click (depends on zoom).

## Steps to reproduce

1. Open some country Page (https://m.gapminder.org/dollar-street/country/55ef338d0d2b3c820378849a)
2. Click the link "See all families in ____" under the Map image.
3. When you had seen matrix, click Back button. At first, page reloads with zoom=4 in URL and after second click "back", you'll back to Country Page.

## Expected result

Button back in all devices should come back user to previous page (internal redirects, like changing zoom=4 to zoom=3 on devices not included in this actions).

## Platform
Mobile, Tablet
## Browsers
All

**Comment by Legionivo** [comment]
@bogdankatrych reproduced

**Comment by Legionivo** [comment]
Verified - fixed
