### ISSUE TITLE
Matrix Page, Country filter: Safari - need to improve styles

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#724]
## Context

Matrix Page, Country filter: Safari - need to improve styles:
 - button OK cut on top
 - String in Search field cut on top

## Steps to reproduce

1. Open Matrix on Safari
2. Open Country filter.

## Current result

 - button OK cut on top
 - String in Search field cut on top

## Platform
MacOS (Macbook Air)

## Browsers
Safari Version 10.0.1 (12602.2.14.0.7)
## `name of issue` screenshot

![screen shot 2016-12-09 at 2 27 01 pm](https://cloud.githubusercontent.com/assets/18209841/21050233/2ed36278-be22-11e6-822a-da4a41190fee.png)

**Comment by Legionivo** [comment]
Verified - fixed
