### ISSUE TITLE
Place Page: some photos are not clickable, BIS can't open

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#725]
## Context

Place Page: some photos are not clickable, BIS didn't open.

## Steps to reproduce

1. Open http://lectures.dollarstreet.org/dollar-street/family?place=54afe95c80d862d9767cf32e&thing=Families&countries=World&regions=World&zoom=4&row=1&lowIncome=26&highIncome=15000
2. Try to click image with thing "Informed consent". This BIS will not open and in console, we get this errors:

`vendor.41ae065….js:3 EXCEPTION: Cannot read property 'replace' of undefined
ErrorHandler.handleError @ vendor.41ae065….js:3
next @ vendor.41ae065….js:4
generatorOrNext.object.schedulerFn @ vendor.41ae065….js:4
SafeSubscriber.__tryOrUnsub @ vendor.41ae065….js:6
SafeSubscriber.next @ vendor.41ae065….js:6
Subscriber._next @ vendor.41ae065….js:6
Subscriber.next @ vendor.41ae065….js:6
Subject.next @ vendor.41ae065….js:6
EventEmitter.emit @ vendor.41ae065….js:4
NgZone.triggerError @ vendor.41ae065….js:4
onHandleError @ vendor.41ae065….js:4
ZoneDelegate.handleError @ polyfills.41ae065….js:5
Zone.runGuarded @ polyfills.41ae065….js:5
NgZone.runGuarded @ vendor.41ae065….js:4
outsideHandler @ vendor.41ae065….js:11
ZoneDelegate.invokeTask @ polyfills.41ae065….js:6
Zone.runTask @ polyfills.41ae065….js:5
ZoneTask.invoke @ polyfills.41ae065….js:6
vendor.41ae065….js:3 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ vendor.41ae065….js:3
next @ vendor.41ae065….js:4
generatorOrNext.object.schedulerFn @ vendor.41ae065….js:4
SafeSubscriber.__tryOrUnsub @ vendor.41ae065….js:6
SafeSubscriber.next @ vendor.41ae065….js:6
Subscriber._next @ vendor.41ae065….js:6
Subscriber.next @ vendor.41ae065….js:6
Subject.next @ vendor.41ae065….js:6
EventEmitter.emit @ vendor.41ae065….js:4
NgZone.triggerError @ vendor.41ae065….js:4
onHandleError @ vendor.41ae065….js:4
ZoneDelegate.handleError @ polyfills.41ae065….js:5
Zone.runGuarded @ polyfills.41ae065….js:5
NgZone.runGuarded @ vendor.41ae065….js:4
outsideHandler @ vendor.41ae065….js:11
ZoneDelegate.invokeTask @ polyfills.41ae065….js:6
Zone.runTask @ polyfills.41ae065….js:5
ZoneTask.invoke @ polyfills.41ae065….js:6
vendor.41ae065….js:3 TypeError: Cannot read property 'replace' of undefined
    at HomeMediaComponent.openMedia (app.41ae065….js:31)
    at _View_HomeMediaComponent1._handle_click_0_0 (HomeMediaComponent.ngfactory.js:265)
    at vendor.41ae065….js:10
    at vendor.41ae065….js:11
    at ZoneDelegate.invoke (polyfills.41ae065….js:5)
    at Object.onInvoke (vendor.41ae065….js:4)
    at ZoneDelegate.invoke (polyfills.41ae065….js:5)
    at Zone.runGuarded (polyfills.41ae065….js:5)
    at NgZone.runGuarded (vendor.41ae065….js:4)
    at HTMLDivElement.outsideHandler (vendor.41ae065….js:11)
ErrorHandler.handleError @ vendor.41ae065….js:3
next @ vendor.41ae065….js:4
generatorOrNext.object.schedulerFn @ vendor.41ae065….js:4
SafeSubscriber.__tryOrUnsub @ vendor.41ae065….js:6
SafeSubscriber.next @ vendor.41ae065….js:6
Subscriber._next @ vendor.41ae065….js:6
Subscriber.next @ vendor.41ae065….js:6
Subject.next @ vendor.41ae065….js:6
EventEmitter.emit @ vendor.41ae065….js:4
NgZone.triggerError @ vendor.41ae065….js:4
onHandleError @ vendor.41ae065….js:4
ZoneDelegate.handleError @ polyfills.41ae065….js:5
Zone.runGuarded @ polyfills.41ae065….js:5
NgZone.runGuarded @ vendor.41ae065….js:4
outsideHandler @ vendor.41ae065….js:11
ZoneDelegate.invokeTask @ polyfills.41ae065….js:6
Zone.runTask @ polyfills.41ae065….js:5
ZoneTask.invoke @ polyfills.41ae065….js:6
polyfills.41ae065….js:5 Uncaught TypeError: Cannot read property 'replace' of undefined
    at HomeMediaComponent.openMedia (app.41ae065….js:31)
    at _View_HomeMediaComponent1._handle_click_0_0 (HomeMediaComponent.ngfactory.js:265)
    at vendor.41ae065….js:10
    at vendor.41ae065….js:11
    at ZoneDelegate.invoke (polyfills.41ae065….js:5)
    at Object.onInvoke (vendor.41ae065….js:4)
    at ZoneDelegate.invoke (polyfills.41ae065….js:5)
    at Zone.runGuarded (polyfills.41ae065….js:5)
    at NgZone.runGuarded (vendor.41ae065….js:4)
    at HTMLDivElement.outsideHandler (vendor.41ae065….js:11)
HomeMediaComponent.openMedia @ app.41ae065….js:31
_View_HomeMediaComponent1._handle_click_0_0 @ HomeMediaComponent.ngfactory.js:265
(anonymous) @ vendor.41ae065….js:10
(anonymous) @ vendor.41ae065….js:11
ZoneDelegate.invoke @ polyfills.41ae065….js:5
onInvoke @ vendor.41ae065….js:4
ZoneDelegate.invoke @ polyfills.41ae065….js:5
Zone.runGuarded @ polyfills.41ae065….js:5
NgZone.runGuarded @ vendor.41ae065….js:4
outsideHandler @ vendor.41ae065….js:11
ZoneDelegate.invokeTask @ polyfills.41ae065….js:6
Zone.runTask @ polyfills.41ae065….js:5
ZoneTask.invoke @ polyfills.41ae065….js:6`

## Expected result

All photos should be clickable

## Possible Fix

This thing is public. And this issue not related to visibility of this thing in Thing-filter.
BTW, if we added this thing to filter, we could easy open BIS with this thing on Matrix Page, but not on Place Page.

## Platform
Linux
## Browsers
Chrome, FF
## `name of issue` screenshot
![screenshot from 2016-12-09 15 26 46](https://cloud.githubusercontent.com/assets/18209841/21050556/088644ee-be24-11e6-841a-0f6e0cf23a7c.png)

**Comment by ludmilanesvitiy** [comment]
It seems, that this issue related to missing thing image. The same issue here with GPS: http://lectures.dollarstreet.org/dollar-street/family?place=5571913377fa3d7747d0016d&thing=Families&countries=Ukraine&regions=World&zoom=4&row=1&lowIncome=26&highIncome=15000

**Comment by Legionivo** [comment]
Unable to reproduce
