### ISSUE TITLE
Matrix Page. Extra low resolution. Header layout issue.

### ISSUE THREAD

**Issue by valentiayka** [Gapminder/dollar-street-pages#739]
Menu button layout issue. Menu goes down in header.

1. User goes to matrix page. Safari, MacOS, width: =/<600px.
2. User can see broken header layout.

## Expected result
Menu has to be in the upper right corner.

## Current result
Menu goes down under filters container.

## Possible Fix
Menu container has 47px width. Filters container has width `calc(100% - 43px)` -> has to be changed to 47px.

## Platform
MacOs 10.12
## Browsers
Safari Version 10.0 (12602.1.50.0.10)

**Comment by valentiayka** [comment]
![matrix_menu_issue](https://cloud.githubusercontent.com/assets/24625904/21331104/77682ab2-c649-11e6-958f-25a92d60a051.png)

**Comment by Ugmaxie** [comment]
Done: https://github.com/Gapminder/dollar-street-pages/pull/741
 @ludmilanesvitiy  please check it out.

**Comment by Legionivo** [comment]
Fixed
