### ISSUE TITLE
Mobile matrix. Free space appears after scrolling down

### ISSUE THREAD

**Issue by bogdankatrych** [Gapminder/dollar-street-pages#787]
## Description
When I screw down on mobile, there is a lot of white space below the street.

![selection_038](https://cloud.githubusercontent.com/assets/17002555/25438183/4ff2b51c-2aa1-11e7-9510-8a92cf73c290.png)

## Steps to reproduce

1. Go to Matrix page
2. Start scrolling down

## Current result
 -  Free space appears according to with screenshot

**Comment by Legionivo** [comment]
Fixed on pre-prod
