### ISSUE TITLE
Tablet view. Incorrect display of top menu 

### ISSUE THREAD

**Issue by bogdankatrych** [Gapminder/dollar-street-pages#788]
## Description
The menu should occupy one row only, not three.

![selection_039](https://cloud.githubusercontent.com/assets/17002555/25438329/c149a9be-2aa1-11e7-8958-f2061cb2b9e8.png)

## Steps to reproduce

1. Open Matrix page 
2. Choose any options of donation.

## Current result
 -  the user is not receiving the notification e-mail 

## Expected result

- When there is no space, "el ingreso económico" should change to $, just like in English.
- When there is no space, language drop down should go to the hamburger menu.

## Device
- Ipad emulation

**Comment by Legionivo** [comment]
Fixed on pre-prod
