### ISSUE TITLE
White space in families names on other languages

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#789]
## Descrption
![selection_039](https://cloud.githubusercontent.com/assets/20966824/25440298/bad81362-2aa7-11e7-9f09-29159836c8cb.png)

## Steps to reproduce

1. Open Matrix Page
2. Click on the any image

## Actual result

White space after family name

## Expected result

No white space after family name

## Device
All

**Comment by Legionivo** [comment]
Fixed on pre-prod
