### ISSUE TITLE
CMS. Increase size of picture being marked

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#795]
## Description

Increase size of picture being marked
When I'm marking things on the picture, it would make it easier for me to identify the thing if the picture was bigger. Right now the picture appears too small and I have to keep zooming in and out. 

## Actual result
![screen shot 2017-04-04 at 13 05 21](https://cloud.githubusercontent.com/assets/20966824/25442082/b6f6ab6e-2aac-11e7-9b46-1831e5cd3b70.png)

## Expected result
![screen shot 2017-04-04 at 13 05 21 2](https://cloud.githubusercontent.com/assets/20966824/25442099/c89606d0-2aac-11e7-842f-f7ebb8bcd79a.png)

**Comment by Legionivo** [comment]
Fixed on pre-prod
