### ISSUE TITLE
Errors while loading matrix page

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/dollar-street-pages#80]
STR:
1. Go to http://consumer.dollarstreet.org/matrix?thing=5477537786deda0b00d43be5&countries=World&regions=World&zoom=5&row=1 .
2. Open browser console.

Actual result:
FFFFFF-undefined:1 GET http://static.dollarstreet.org.s3.amazonaws.com/thing/560cfcae560dd0ac27fc410f/FFFFFF-undefined 403 (Forbidden)

Expected result:
There should be no errors.

**Comment by ghost** [comment]
Still reproducible.

`undefined:1 GET http://consumer.dollarstreet.org/undefined 404 (Not Found)`

**Comment by ludmilanesvitiy** [comment]
Still reproducible.
GET 
http://consumer.dollarstreet.org/undefined [HTTP/1.1 404 Not Found 140ms]
GET 
http://consumer.dollarstreet.org/null [HTTP/1.1 404 Not Found 141ms]

**Comment by ludmilanesvitiy** [comment]
Still reproducible:
Failed to load resource: the server responded with a status of 404 (Not Found)
