### ISSUE TITLE
Make search of things return better results

### ISSUE THREAD

**Issue by Legionivo** [Gapminder/dollar-street-pages#864]
## Context

When I search "Toilets" thing search result show "Bathrooms" and "Toilets". "Bathrooms" is first result. Why? And why it showed here? 

## Steps to reproduce

1. Go to DS main page.
2. Open Families and type "Toilets" in search field.

## Expected result

Search result contains only "Toilets" or make it work as it implemented now, but return search phrase as first result.

## Current result

Search results contains "Bathrooms" on the first place and "Toilets" on second

![07_07_11-15-27_01](https://user-images.githubusercontent.com/12167296/27949622-fc4fde14-6306-11e7-9270-74d766f0c5e5.png)

**Comment by dmitryuck** [comment]
This is not an issue, things search uses synonyms, the results are not only the word you searching and related to it other things

**Comment by Legionivo** [comment]
Ok, then make search a bit better, so it will return searched item together with synonyms, but on the first place.
