### ISSUE TITLE
(ngrx-integration) Zoom buttons shifted right in Firefox and need to implement limit for zoom action

### ISSUE THREAD

**Issue by Legionivo** [Gapminder/dollar-street-pages#872]
## Context

Zoom buttons shifted right. See screenshot

![07_20_10 23 29_01](https://user-images.githubusercontent.com/12167296/28413034-c8bc7812-6d4e-11e7-89f2-9a98623405c8.png)

**Comment by dmitryuck** [comment]
Need to implement zoom limit

**Comment by Legionivo** [comment]
reproduced
