### ISSUE TITLE
(ngrx-integration) Error happens when mobile emulator enabled in Chrome

### ISSUE THREAD

**Issue by Legionivo** [Gapminder/dollar-street-pages#875]
## Context

When mobile device emulator enabled in Chrome I observe errors in console. See attached image.

## Browsers
Chrome

![07_20_11 50 23_01](https://user-images.githubusercontent.com/12167296/28413421-1a49affa-6d50-11e7-9b99-55d2e57c19e1.png)

**Comment by dmitryuck** [comment]
Need steps for reproduce

**Comment by Legionivo** [comment]
@mdmitriy it doesn't reproduce anymore, closing it
