### ISSUE TITLE
Things on family page sometimes not shown

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#886]
## Context

![123](https://user-images.githubusercontent.com/20966824/28911545-90be5f48-7839-11e7-9508-0a0d3ecbae8d.jpeg)

Sometimes block with family images displayed empty

## Steps to reproduce

1. Open matrix page
2. Click on any image
3. Click "Visit this home"

## Expected result

Family page opens and family things are shown

## Current result

Family page opens but family things may not be shown

## Platform
All

## Browsers
All

**Comment by Legionivo** [comment]
Verified - fixed
