### ISSUE TITLE
Matrix page content could be scrolled under opened filter(Related and Popular sections)

### ISSUE THREAD

**Issue by bogdankatrych** [Gapminder/dollar-street-pages#902]
## Context

In case if a user opens some filter  Families and hover on Related or Popular section and starts scrolling to the end of filters list, matrix page content is being scrolled too. 

## Steps to reproduce

1. Open Matrix page
2. Open Filters list, hover to Related and Popular section
3. Scroll to the end of the list

## Expected result

Page content under opened filters list shouldn't be scrolled

## Current result

Page content under filters list scrolls 

## Platform
Any

## Browsers
Any

**Comment by Legionivo** [comment]
Verified - fixed
