### ISSUE TITLE
Share feature: markup issue with header on small screen

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/dollar-street-pages#954]
## Context

On small screens (e.g. less than 1000 px) when a lot of text in the header buttons moved outside the block

## Steps to reproduce

1. Choose 6 families
2. Check the buttons

## Expected result

The buttons are in the right place

## Current result

The buttons moved outside the block

## Possible Fix

Maybe we can hide "extra" text by "..."

## Platform
any
## Browsers
any
## screenshot

![selection_031](https://user-images.githubusercontent.com/18219232/30330931-10ce12fe-97df-11e7-89ad-5fe2dd3ad448.png)

**Comment by bogdankatrych** [comment]
@mikhailvoloshin Need your suggestions according to the screenshot
