### ISSUE TITLE
EXPERIMENTAL. Family income on family page

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#989]
## Context

![currency_family_page](https://user-images.githubusercontent.com/20966824/30803614-e993f41a-a1f2-11e7-8274-552e5ea1dd2c.jpeg)

## Steps to reproduce

1. Open matrix page
2. Oen income filter and choose another currency/time unit
3. Open family in BIS
4. Visit selected family

## Expected result

Family income should be displayed according to income filter options

## Current result

Family income is shown only dollars/month

## Platform
Desktop

## Browsers
Any

**Comment by sergeyKhristenko** [comment]
And also Floating header in this page

![selection_086](https://user-images.githubusercontent.com/18219232/30805590-b515c74c-a1fa-11e7-9a30-04804ca45bde.png)
