### ISSUE TITLE
EXPERIMENTAL. Family income value on map page

### ISSUE THREAD

**Issue by dmitryuck** [Gapminder/dollar-street-pages#990]
## Context

![currency_map](https://user-images.githubusercontent.com/20966824/30803880-f5cad888-a1f3-11e7-8de6-813be36afde4.jpeg)

## Steps to reproduce

1. Open matrix
2. Open income filter
3. Change income filter options (currency/time unit)
4. Open map page
5. Hover any place on the map

## Expected result

Family income should be displayed according to income filter options

## Current result

Family income displays only with dollar/month format

## Platform
Desktop

## Browsers
Any

**Comment by sergeyKhristenko** [comment]
Settings should be stored in URL. Create another issue for that.
